# Generated by Django 4.0.8 on 2022-12-20 06:22

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(error_messages={'unique': 'Конкурс с таким названием уже существует!'}, max_length=40, unique=True, verbose_name='Название конкурса')),
                ('Short_Description', models.CharField(max_length=110, verbose_name='Краткое описание')),
                ('Document', models.FileField(upload_to=main.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Документ')),
                ('Date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('Language', models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык')),
                ('Status', models.CharField(choices=[('Актуально', 'Актуально'), ('Проведён', 'Проведён'), ('Не Проведён', 'Не Проведён')], default='Актуально', max_length=20, verbose_name='Статус')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(error_messages={'unique': 'Галерея с таким названием уже существует!'}, max_length=70, unique=True, verbose_name='Название галереи')),
            ],
            options={
                'db_table': 'galleryNews',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(error_messages={'unique': 'Галерея с таким названием уже существует!'}, max_length=70, unique=True, verbose_name='Название галереи')),
            ],
            options={
                'db_table': 'galleryProject',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HotNewsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Галерея с таким названием уже существует!'}, max_length=50, unique=True, verbose_name='Название галереи')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Такая запись уже существует!'}, max_length=80, unique=True, verbose_name='Название ссылки')),
                ('link', models.CharField(max_length=2048, validators=[main.models.check_link_validate], verbose_name='Ссылка на статью')),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, verbose_name='ФИО Сотрудника')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('date_birth', models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения')),
                ('about', ckeditor.fields.RichTextField(verbose_name='Биография сотрудника')),
                ('mail_link', models.CharField(max_length=2080, null=True, verbose_name='Ссылка на почту')),
                ('instagram_link', models.CharField(max_length=2080, null=True, verbose_name='Ссылка на инстаграм')),
                ('facebook_link', models.CharField(max_length=2080, null=True, verbose_name='Ссылка на facebook')),
                ('language', models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык')),
                ('picture', models.ImageField(upload_to=main.models.get_file_path, validators=[django.core.validators.validate_image_file_extension], verbose_name='Фотография')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(error_messages={'unique': 'Категория с таким названием уже существует!'}, max_length=70, unique=True, verbose_name='Название категории')),
            ],
            options={
                'db_table': 'projectCategory',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Отчет с таким названием уже существует!'}, max_length=80, unique=True, verbose_name='Название отчета')),
                ('short_description', models.CharField(max_length=130, verbose_name='Краткое описание')),
                ('language', models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык')),
                ('url', models.FileField(upload_to=main.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Путь файла')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Вакансия уже существует!'}, max_length=70, unique=True, verbose_name='Заголовок')),
                ('company', models.CharField(max_length=70, verbose_name='Компания')),
                ('Language', models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата размещения')),
                ('positions', models.CharField(max_length=70, verbose_name='Должность')),
                ('salary', models.CharField(max_length=70, verbose_name='Оклад')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('Актуально', 'Актуально'), ('Данная вакансия не актуальна', 'Данная вакансия не актуальна')], default='Актуально', max_length=30, verbose_name='Статус')),
                ('email_company', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(error_messages={'unique': 'Проект с таким названием уже существует!'}, max_length=120, unique=True, verbose_name='Заголовок проекта')),
                ('Short_Description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('Description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('Date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('Language', models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык')),
                ('Status', models.CharField(choices=[('В перспективе', 'В перспективе'), ('Реализованные', 'Реализованные')], default='В перспективе', max_length=20, verbose_name='Статус')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.projectcategory', verbose_name='Категория')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.galleryproject', verbose_name='Галерея')),
            ],
        ),
        migrations.CreateModel(
            name='PhotosProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.ImageField(upload_to=main.models.get_file_path, verbose_name='Путь к картинке')),
                ('Caption', models.CharField(max_length=110, verbose_name='Название картинки')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.galleryproject', verbose_name='Галерея')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PhotosNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.ImageField(upload_to=main.models.get_file_path, validators=[django.core.validators.validate_image_file_extension], verbose_name='Путь картинки')),
                ('Caption', models.CharField(max_length=70, verbose_name='Название картинки')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.gallerynews', verbose_name='Галерея')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(error_messages={'unique': 'Новость с таким названием уже существует!'}, max_length=100, unique=True, verbose_name='Заголовок новости')),
                ('Short_Description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('Description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('Date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('Language', models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.gallerynews', verbose_name='Галерея')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HotNewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=70, verbose_name='Название фотографии')),
                ('url', models.ImageField(upload_to=main.models.get_file_path, validators=[django.core.validators.validate_image_file_extension], verbose_name='Путь картинки')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.hotnewsgallery', verbose_name='Галерея')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HotNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Событие с таким названием уже существует!'}, max_length=150, unique=True, verbose_name='Название событии')),
                ('short_description', models.CharField(max_length=220, verbose_name='Краткое описание')),
                ('description', ckeditor.fields.RichTextField()),
                ('Language', models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.hotnewsgallery', verbose_name='Галерея')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
