# Generated by Django 4.0.8 on 2022-12-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='Title',
            field=models.CharField(error_messages={'unique': 'Конкурс с таким названием уже существует!'}, max_length=40, unique=True, verbose_name='Название конкурса'),
        ),
        migrations.AlterField(
            model_name='gallerynews',
            name='Name',
            field=models.CharField(error_messages={'unique': 'Галерея с таким названием уже существует!'}, max_length=50, unique=True, verbose_name='Название галереи'),
        ),
        migrations.AlterField(
            model_name='galleryproject',
            name='Name',
            field=models.CharField(error_messages={'unique': 'Галерея с таким названием уже существует!'}, max_length=50, unique=True, verbose_name='Название галереи'),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='title',
            field=models.CharField(error_messages={'unique': 'Событие с таким названием уже существует!'}, max_length=70, unique=True, verbose_name='Название событии'),
        ),
        migrations.AlterField(
            model_name='hotnewsgallery',
            name='name',
            field=models.CharField(error_messages={'unique': 'Галерея с таким названием уже существует!'}, max_length=50, unique=True, verbose_name='Название галереи'),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='title',
            field=models.CharField(error_messages={'unique': 'Такая запись уже существует!'}, max_length=80, unique=True, verbose_name='Название ссылки'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.CharField(error_messages={'unique': 'Новость с таким названием уже существует!'}, max_length=100, unique=True, verbose_name='Заголовок новости'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='Name',
            field=models.CharField(error_messages={'unique': 'Категория с таким названием уже существует!'}, max_length=70, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Title',
            field=models.CharField(error_messages={'unique': 'Проект с таким названием уже существует!'}, max_length=70, unique=True, verbose_name='Заголовок проекта'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='title',
            field=models.CharField(error_messages={'unique': 'Отчет с таким названием уже существует!'}, max_length=80, unique=True, verbose_name='Название отчета'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='title',
            field=models.CharField(error_messages={'unique': 'Вакансия уже существует!'}, max_length=70, unique=True, verbose_name='Заголовок'),
        ),
    ]
