# Generated by Django 4.0.8 on 2022-12-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosproject',
            name='Caption',
            field=models.CharField(max_length=200, verbose_name='Название картинки'),
        ),
    ]
