# Generated by Django 4.1.3 on 2022-12-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contests_title_alter_gallerynews_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='facebook_link',
            field=models.CharField(max_length=2080, null=True, verbose_name='Ссылка на facebook'),
        ),
        migrations.AddField(
            model_name='management',
            name='instagram_link',
            field=models.CharField(max_length=2080, null=True, verbose_name='Ссылка на инстаграм'),
        ),
        migrations.AddField(
            model_name='management',
            name='mail_link',
            field=models.CharField(max_length=2080, null=True, verbose_name='Ссылка на почту'),
        ),
    ]
