# Generated by Django 4.0.8 on 2022-12-19 18:47

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contests_title_alter_gallerynews_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerynews',
            name='Name',
            field=models.CharField(error_messages={'unique': 'Галерея с таким названием уже существует!'}, max_length=70, unique=True, verbose_name='Название галереи'),
        ),
        migrations.AlterField(
            model_name='galleryproject',
            name='Name',
            field=models.CharField(error_messages={'unique': 'Галерея с таким названием уже существует!'}, max_length=70, unique=True, verbose_name='Название галереи'),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='short_description',
            field=models.CharField(max_length=220, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='title',
            field=models.CharField(error_messages={'unique': 'Событие с таким названием уже существует!'}, max_length=150, unique=True, verbose_name='Название событии'),
        ),
        migrations.AlterField(
            model_name='hotnewsphoto',
            name='caption',
            field=models.CharField(max_length=70, verbose_name='Название фотографии'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Short_Description',
            field=models.CharField(max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='photosproject',
            name='Caption',
            field=models.CharField(max_length=110, verbose_name='Название картинки'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Short_Description',
            field=models.CharField(max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Title',
            field=models.CharField(error_messages={'unique': 'Проект с таким названием уже существует!'}, max_length=120, unique=True, verbose_name='Заголовок проекта'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='url',
            field=models.FileField(upload_to=main.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Путь файла'),
        ),
    ]
