# Generated by Django 4.0.8 on 2022-12-29 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_photosproject_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='Date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Short_Description',
            field=models.CharField(max_length=250, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Title',
            field=models.CharField(error_messages={'unique': 'Конкурс с таким названием уже существует!'}, max_length=150, unique=True, verbose_name='Название конкурса'),
        ),
        migrations.AlterField(
            model_name='photosnews',
            name='Caption',
            field=models.CharField(max_length=200, verbose_name='Название картинки'),
        ),
    ]
