# Generated by Django 4.1.3 on 2022-12-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_management_facebook_link_management_instagram_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='education',
        ),
        migrations.RemoveField(
            model_name='management',
            name='speciality',
        ),
    ]
