# Generated by Django 4.0.8 on 2022-11-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_contestscategory_delete_gallerycontests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='Short_Description',
            field=models.CharField(default='dcdcdfvdfbggggggggg', max_length=110, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
