# Generated by Django 4.0.8 on 2022-11-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_contests_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Short_Description',
            field=models.CharField(default='dsdsd', max_length=110, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
