# Generated by Django 4.0.8 on 2022-11-21 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_projects_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=70, verbose_name='Компания')),
                ('Language', models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата размещения')),
                ('positions', models.CharField(max_length=70, verbose_name='Должность')),
                ('salary', models.CharField(max_length=70, verbose_name='Оклад')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('Актуально', 'Актуально'), ('Данная вакансия не актуальна', 'Данная вакансия не актуальна')], default='Актуально', max_length=30, verbose_name='Статус')),
                ('email_company', models.EmailField(max_length=254)),
            ],
        ),
    ]
