# Generated by Django 4.0.8 on 2022-11-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='title',
            field=models.CharField(default=' ', max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
