# Generated by Django 4.0.8 on 2022-11-22 14:27

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_vacancies_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, verbose_name='ФИО Сотрудника')),
                ('position', models.CharField(max_length=70, verbose_name='Должность')),
                ('about', ckeditor.fields.RichTextField(verbose_name='Биография сотрудника')),
                ('picture', models.ImageField(upload_to=main.models.get_file_path, validators=[django.core.validators.validate_image_file_extension], verbose_name='Фотография')),
            ],
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='contests',
            name='Title',
            field=models.CharField(max_length=40, verbose_name='Название конкурса'),
        ),
        migrations.AlterField(
            model_name='photosproject',
            name='URL',
            field=models.ImageField(upload_to=main.models.get_file_path, verbose_name='Путь к картинке'),
        ),
    ]
