# Generated by Django 4.0.8 on 2022-11-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_management_alter_projectcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosproject',
            name='Caption',
            field=models.CharField(max_length=70, verbose_name='Название картинки'),
        ),
    ]
