# Generated by Django 4.0.8 on 2022-11-22 14:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_photosproject_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
