# Generated by Django 4.0.8 on 2022-11-24 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_news_description_alter_projects_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='date_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='management',
            name='education',
            field=models.CharField(default='', max_length=60, verbose_name='Образования'),
        ),
        migrations.AddField(
            model_name='management',
            name='speciality',
            field=models.CharField(default='', max_length=30, verbose_name='Специальность'),
        ),
    ]
