# Generated by Django 4.0.8 on 2022-11-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_management_date_birth_management_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='education',
            field=models.CharField(max_length=60, verbose_name='Образования'),
        ),
        migrations.AlterField(
            model_name='management',
            name='speciality',
            field=models.CharField(max_length=30, verbose_name='Специальность'),
        ),
    ]
