# Generated by Django 4.0.8 on 2022-11-25 06:40

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_management_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotNewsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название галереи')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='email_company',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='HotNewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=70, verbose_name='Название фотографии')),
                ('url', models.ImageField(upload_to=main.models.get_file_path, validators=[django.core.validators.validate_image_file_extension], verbose_name='Путь картинки')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.hotnewsgallery', verbose_name='Галерея')),
            ],
        ),
        migrations.CreateModel(
            name='HotNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название событии')),
                ('short_description', models.CharField(max_length=120, verbose_name='Краткое описание')),
                ('description', ckeditor.fields.RichTextField()),
                ('Language', models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.hotnewsgallery', verbose_name='Галерея')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
