# Generated by Django 4.0.8 on 2022-11-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_hotnewsgallery_alter_vacancies_email_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='Language',
            field=models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='short_description',
            field=models.CharField(max_length=100, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='hotnewsgallery',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название галереи'),
        ),
        migrations.AlterField(
            model_name='hotnewsphoto',
            name='caption',
            field=models.CharField(max_length=50, verbose_name='Название фотографии'),
        ),
    ]
