# Generated by Django 4.0.8 on 2022-11-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_hotnewsphoto_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='Language',
            new_name='language',
        ),
        migrations.AlterField(
            model_name='management',
            name='full_name',
            field=models.CharField(max_length=60, verbose_name='ФИО Сотрудника'),
        ),
        migrations.AlterField(
            model_name='management',
            name='speciality',
            field=models.CharField(max_length=40, verbose_name='Специальность'),
        ),
    ]
