# Generated by Django 4.0.8 on 2022-12-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_news_options_alter_news_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Short_Description',
            field=models.CharField(max_length=170, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.CharField(max_length=100, verbose_name='Заголовок новости'),
        ),
    ]
