# Generated by Django 4.1.3 on 2022-12-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_news_short_description_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название интервью')),
                ('short_description', models.CharField(max_length=130, verbose_name='Краткое описание')),
                ('link', models.CharField(max_length=2048, verbose_name='Ссылка на статью')),
            ],
        ),
        migrations.AlterField(
            model_name='management',
            name='education',
            field=models.CharField(max_length=255, verbose_name='Образования'),
        ),
        migrations.AlterField(
            model_name='management',
            name='speciality',
            field=models.CharField(max_length=255, verbose_name='Специальность'),
        ),
    ]
