# Generated by Django 4.1.3 on 2022-12-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_interviews_alter_management_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Status',
            field=models.CharField(choices=[('В перспективе', 'В перспективе'), ('Реализованные', 'Реализованные')], default='В перспективе', max_length=20, verbose_name='Статус'),
        ),
    ]
